name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm ci

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm ci
      - run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor}}@users.noreply.github.com"
            npx lerna run build
            git add .
            git commit -m "chore: build packages"
            git push
            npx lerna version --conventional-commits --conventional-graduate --yes
            npx lerna publish from-git --yes
